export { WorkspaceRole } from "@prisma/client";

export enum WorkspacePermission {
  CREATE_PROJECT = "CREATE_PROJECT",
  INVITE_MEMBER = "INVITE_MEMBER",
  REMOVE_MEMBER = "REMOVE_MEMBER",
  ADD_MEMBER = "ADD_MEMBER",
  UPDATE_MEMBER_ROLE = "UPDATE_MEMBER_ROLE",
  VIEW_INVITATIONS = "VIEW_INVITATIONS",
  CANCEL_INVITATION = "CANCEL_INVITATION",
  UPDATE_WORKSPACE = "UPDATE_WORKSPACE",
  DELETE_WORKSPACE = "DELETE_WORKSPACE",
  VIEW_WORKSPACE = "VIEW_WORKSPACE",
}
